pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    blogPostOgImage:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 1200
                                    height: 630
                                    positioning: center
                                    forceResize: true
                        medias: {  }
                        name: blogPostOgImage
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1732898697
                        creationDate: 1732898670
                        preserveAnimation: false
