pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    galleryCarouselPreview:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 100
                                    height: 54
                                    positioning: center
                                    forceResize: false
                        medias: {  }
                        name: galleryCarouselPreview
                        description: ''
                        group: Areas
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1732690415
                        creationDate: 1732690371
                        preserveAnimation: false
